"""empty message

Revision ID: 719c5df6242a
Revises: bf4013dac0b6
Create Date: 2024-12-05 15:09:58.484812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719c5df6242a'
down_revision: Union[str, None] = 'bf4013dac0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resident', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('resident', sa.Column('name', sa.String(), nullable=False))
    op.add_column('resident', sa.Column('patronymics', sa.String(), nullable=True))
    op.drop_column('resident', 'snp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resident', sa.Column('snp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('resident', 'patronymics')
    op.drop_column('resident', 'name')
    op.drop_column('resident', 'surname')
    # ### end Alembic commands ###
