"""empty message

Revision ID: 5fe2eeb027e0
Revises: 7e051031b097
Create Date: 2024-12-13 12:39:17.959791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe2eeb027e0'
down_revision: Union[str, None] = '7e051031b097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_until_date', table_name='task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_until_date', 'task', ['until_date'], unique=False)
    # ### end Alembic commands ###
