"""empty message

Revision ID: 7e051031b097
Revises: a7ecf56d944e
Create Date: 2024-12-13 12:35:03.067626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e051031b097'
down_revision: Union[str, None] = 'a7ecf56d944e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_until_date'), 'task', ['until_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_until_date'), table_name='task')
    # ### end Alembic commands ###
