"""empty message

Revision ID: cb8e3256ea65
Revises: 304d95d2ddc4
Create Date: 2024-12-13 13:08:26.065466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8e3256ea65'
down_revision: Union[str, None] = '304d95d2ddc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_until_date'), 'payment', ['until_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_until_date'), table_name='payment')
    # ### end Alembic commands ###
